language: node_js
node_js:
  - "13"

cache:
  directories:
    - "node_modules"

install:
  - npm install

addons:
  postgresql: 9.6
  apt:
    packages:
      - postgresql-9.6-postgis-2.3

before_script:
  - psql -c 'CREATE DATABASE $DB_TEST_NAME;' -U postgres
  - psql -c "CREATE USER $DB_TEST_USER WITH PASSWORD '$DB_TEST_PASS';" -U postgres
  - psql -d $DB_TEST_NAME -c "CREATE EXTENSION postgis" -U postgres
  - psql -c "ALTER DATABASE $DB_TEST_NAME OWNER TO $DB_TEST_USER"

script:
  - npm test
