language: node_js
node_js:
  - "13"

cache:
  directories:
    - "node_modules"

install:
  - npm install

addons:
  postgresql: 9.6
  apt:
    packages:
      - postgresql-9.6-postgis-2.3

before_script:
  - psql -c 'CREATE DATABASE travis_test;' -U postgres
  - psql -c "CREATE USER temp WITH PASSWORD 'test';" -U postgres
  - psql -d travis_test -c "CREATE EXTENSION postgis"
  - psql -c "ALTER DATABASE travis_test OWNER TO temp"

script:
  - npm test
