language: node_js
node_js:
  - "13"

cache:
  directories:
    - "node_modules"

install:
  - npm install

addons:
  postgresql: 9.6
  apt:
    packages:
      - postgresql-9.6-postgis-2.3

before_script:
  - psql -c 'create database travis_test;' -U postgres
  - psql -c "CREATE USER travis WITH PASSWORD test;" -U postgres
  - psql -d travis_test -c "create extension postgis"
  - psql -c "ALTER DATABASE travis_test OWNER TO travis"

script:
  - npm test
